version: '3.8'

services:
  count-of-money-front:
    build: ./frontend
    container_name: count-of-money-front
    ports:
      - "3000:3000"
    environment: 
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./frontend:/app"
      - "./frontend/node_modules:/app/node_modules"

  count-of-money-api:
    build: ./api
    container_name: count-of-money-api
    ports:
      - "4000:4000"
    volumes:
      - "./api:/app"